name: Deploy Frontend Angular

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Angular production
        run: npm run build -- --configuration production --base-href /

      - name: Copy dist to Docker build context (datasweb)
        run: |
          rm -rf datasweb/*
          cp -r dist/* datasweb/

      - name: Build Docker image
        run: docker build -t seu-frontend-image:latest ./datasweb

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push seu-frontend-image:latest

      - name: Deploy in VPS via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull seu-frontend-image:latest

            if docker ps -q -f name=frontend-app; then
              echo "Parando container frontend-app..."
              docker stop frontend-app
            fi

            if docker ps -aq -f name=frontend-app; then
              echo "Removendo container frontend-app..."
              docker rm frontend-app
            fi

            echo "Iniciando novo container frontend-app..."
            docker run -d -p 8081:80 --name frontend-app seu-frontend-image:latest

            echo "Deploy frontend concluído com sucesso!"
