name: Deploy Frontend Angular via Zip

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build Angular production
        run: npm run build --prod

      - name: Zip dist folder
        run: |
          cd dist
          zip -r ../dist.zip .

      - name: Copy dist.zip to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "dist.zip"
          target: "/tmp/"

      - name: Unzip dist.zip and rebuild container on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            rm -rf /var/www/datasweb/*
            unzip /tmp/dist.zip -d /var/www/datasweb/
            cp /tmp/Dockerfile /var/www/datasweb/
            cp /tmp/nginx-prod-front.conf /var/www/datasweb/
            rm /tmp/dist.zip
            docker build --no-cache -t seu-frontend-image:latest /var/www/datasweb/
            docker stop frontend-app || true
            docker rm frontend-app || true
            docker-compose -f /root/prod/docker-compose.prod.yml up -d --build frontend
